HOSTS:
  ca:
    roles:
      - ca
      - server
      - default
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: vagrant
    vagrant_memsize: 4096
    vagrant_cpus: 4
    yum_repos:
      epel:
        url: 'http://download.fedoraproject.org/pub/epel/7/$basearch'
        gpgkeys:
          - https://getfedora.org/static/352C64E5.txt

  el7:
    roles:
      - client
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: vagrant
    yum_repos:
      epel:
        url: 'http://download.fedoraproject.org/pub/epel/7/$basearch'
        gpgkeys:
          - https://getfedora.org/static/352C64E5.txt

  el6:
    roles:
      - client
    platform:   el-6-x86_64
    box:        centos/6
    hypervisor: vagrant
    yum_repos:
      epel:
        url: 'http://download.fedoraproject.org/pub/epel/6/$basearch'
        gpgkeys:
          - https://getfedora.org/static/0608B895.txt

CONFIG:
  log_level: verbose
  type:      aio
